---

env:
    browser: true
    es6: true
    jest: true

plugins:
    - '@typescript-eslint'

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    - 'plugin:jest/recommended'
    - 'plugin:prettier/recommended'
    - 'prettier/@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
    project: 'tsconfig.json'
    tsconfigRootDir: '.'
